
import { LessonContent } from './types';

export const VIETNAMESE_LESSONS: LessonContent[] = [
  // ================= TẬP 1: ÂM, CHỮ VÀ VẦN (83 BÀI) =================
  { id: 1, title: "Bài 1: A a", letters: ["a"], recognitionSentence: "Nam và Hà ca hát.", vocabulary: ["ba", "ca", "hà", "lá"], readingText: "a", imagePrompt: "Nam và Hà đang cầm micro hát vui vẻ trên sân khấu ngoài trời" },
  { id: 2, title: "Bài 2: B b `", letters: ["b", "`"], recognitionSentence: "Bà cho bé búp bê.", vocabulary: ["ba", "bà", "bố", "bé"], readingText: "ba, bà, ba ba", imagePrompt: "Người bà hiền hậu đang tặng búp bê cho bé gái" },
  { id: 3, title: "Bài 3: C c /", letters: ["c", "/"], recognitionSentence: "Nam và bố câu cá.", vocabulary: ["ca", "cà", "cá", "cò"], readingText: "A, cá.", imagePrompt: "Nam và bố ngồi câu cá bên hồ, Nam reo hò khi thấy cá" },
  { id: 4, title: "Bài 4: E e Ê ê", letters: ["e", "ê"], recognitionSentence: "Bé kể mẹ nghe về bạn bè.", vocabulary: ["bè", "bé", "bế"], readingText: "Bà bế bé.", imagePrompt: "Bé ngồi cạnh mẹ kể chuyện, trên bàn có đĩa quả lê" },
  { id: 5, title: "Bài 5: Ôn tập và kể chuyện", letters: ["a", "b", "c", "e", "ê"], recognitionSentence: "Bé ôn lại các chữ đã học.", vocabulary: ["ba", "bà", "cá", "bê"], readingText: "Bé vẽ cá, bé vẽ lê.", imagePrompt: "Bé ngồi học bài chăm chỉ với bảng chữ cái màu sắc" },
  { id: 6, title: "Bài 6: O o ?", letters: ["o", "?"], recognitionSentence: "Đàn bò gặm cỏ.", vocabulary: ["bò", "cò", "cỏ"], readingText: "Bê có cỏ.", imagePrompt: "Cánh đồng cỏ xanh có đàn bò đang gặm cỏ" },
  { id: 7, title: "Bài 7: Ô ô .", letters: ["ô", "."], recognitionSentence: "Bố và Hà đi bộ trên hè phố.", vocabulary: ["bố", "cô bé", "cổ cò"], readingText: "Bố bế bể cá.", imagePrompt: "Bố nắm tay Hà đi bộ trên vỉa hè phố phường" },
  { id: 8, title: "Bài 8: D d Đ đ", letters: ["d", "đ"], recognitionSentence: "Dưới gốc đa, các bạn chơi dung dăng dung dẻ.", vocabulary: ["đá dế", "đa đa", "ô đỏ"], readingText: "Bé có ô đỏ.", imagePrompt: "Nhóm bạn nhỏ chơi dung dăng dung dẻ dưới gốc cây đa" },
  { id: 9, title: "Bài 9: Ơ ơ ~", letters: ["ơ", "~"], recognitionSentence: "Tàu dỡ hàng ở cảng.", vocabulary: ["bờ đê", "cá cờ", "đỡ bé"], readingText: "Bố đỡ bé.", imagePrompt: "Cảnh cảng biển có tàu lớn đang bốc dỡ hàng hóa" },
  { id: 10, title: "Bài 10: Ôn tập và kể chuyện", letters: ["o", "ô", "ơ", "d", "đ"], recognitionSentence: "Bé ôn chữ và dấu thanh.", vocabulary: ["cờ", "đỡ", "bố", "đá"], readingText: "Bố bế bé đi bộ.", imagePrompt: "Gia đình đi dạo công viên vui vẻ" },
  { id: 11, title: "Bài 11: I i K k", letters: ["i", "k"], recognitionSentence: "Nam vẽ kì đà.", vocabulary: ["bí đỏ", "kẻ ô", "đi bộ", "kì đà"], readingText: "Kì đà bò ở kẽ đá.", imagePrompt: "Bé Nam ngồi vẽ hình con kì đà vào vở bài tập" },
  { id: 12, title: "Bài 12: H h L l", letters: ["h", "l"], recognitionSentence: "Le le bơi trên hồ.", vocabulary: ["lá đỏ", "bờ hồ", "cá hố", "le le"], readingText: "Bé bị ho. Bà đã có lá hẹ.", imagePrompt: "Đàn chim le le đang bơi lội thong thả trên mặt hồ" },
  { id: 13, title: "Bài 13: U u Ư ư", letters: ["u", "ư"], recognitionSentence: "Đu đủ chín ngọt lừ.", vocabulary: ["dù", "đu đủ", "hổ dữ"], readingText: "Cá hổ là cá dữ.", imagePrompt: "Bé gái đang ngồi ăn những miếng đu đủ chín vàng" },
  { id: 14, title: "Bài 14: Ch ch Kh kh", letters: ["ch", "kh"], recognitionSentence: "Mấy chú khỉ ăn chuối.", vocabulary: ["lá khô", "chú khỉ", "chợ cá"], readingText: "Chị có cá kho khế.", imagePrompt: "Những chú khỉ tinh nghịch đang ngồi ăn chuối trong rừng" },
  { id: 16, title: "Bài 16: M m N n", letters: ["m", "n"], recognitionSentence: "Mẹ mua nơ cho Hà.", vocabulary: ["má", "mẹ", "na", "ca nô"], readingText: "Bố mẹ cho Hà đi ca nô.", imagePrompt: "Mẹ dắt Hà đi mua sắm, mẹ chọn cho Hà một chiếc nơ màu đỏ" },
  { id: 17, title: "Bài 17: G g Gi gi", letters: ["g", "gi"], recognitionSentence: "Hà có giỏ trứng gà.", vocabulary: ["gà gô", "đồ gỗ", "giá đỗ"], readingText: "Bà che gió cho ba chú gà.", imagePrompt: "Bé Hà đang cầm một chiếc giỏ đựng đầy trứng gà" },
  { id: 18, title: "Bài 18: Gh gh Nh nh", letters: ["gh", "nh"], recognitionSentence: "Hà ghé nhà bà. Nhà bà ở ngõ nhỏ.", vocabulary: ["ghế đá", "ghẹ đỏ", "nhà gỗ"], readingText: "Mẹ nhờ Hà bê ghế nhỏ.", imagePrompt: "Cảnh Hà bước vào một ngôi nhà cổ kính trong ngõ nhỏ" },
  { id: 19, title: "Bài 19: Ng ng Ngh ngh", letters: ["ng", "ngh"], recognitionSentence: "Nghé theo mẹ ra ngõ.", vocabulary: ["ngã ba", "ngõ nhỏ", "củ nghệ"], readingText: "Nghé đã no cỏ. Nghé ngủ ở bờ đê.", imagePrompt: "Chú nghé con đang lon ton đi theo mẹ trâu trên đường làng" },
  { id: 21, title: "Bài 21: R r S s", letters: ["r", "s"], recognitionSentence: "Bầy sẻ non ríu ra ríu rít bên mẹ.", vocabulary: ["rổ rá", "cá rô", "su su"], readingText: "Chợ có gà ri, cá rô, su su. Chợ có cả rổ rá.", imagePrompt: "Tổ chim sẻ trên cành cây tre, chim mẹ đang mớm mồi" },
  { id: 22, title: "Bài 22: T t Tr tr", letters: ["t", "tr"], recognitionSentence: "Nam tô bức tranh cây tre.", vocabulary: ["ô tô", "sư tử", "cá trê"], readingText: "Hà tả hồ cá. Hồ to, có cá mè, cá trê, cá rô.", imagePrompt: "Bé Nam đang dùng bút màu tô bức tranh rặng tre xanh" },
  { id: 23, title: "Bài 23: Th th ia", letters: ["th", "ia"], recognitionSentence: "Trung thu, bé được chia quà.", vocabulary: ["thủ đô", "lá thư", "thìa dĩa"], readingText: "Bé chia thìa, chia dĩa cho cả nhà. Thìa dĩa to cho bố mẹ.", imagePrompt: "Cảnh các em nhỏ rước đèn ông sao dưới ánh trăng rằm" },
  { id: 24, title: "Bài 24: ua ưa", letters: ["ua", "ưa"], recognitionSentence: "Mẹ đưa Hà đến lớp học múa.", vocabulary: ["cà chua", "múa ô", "dưa lê"], readingText: "Mẹ đi chợ mua cá, mua cua. Mẹ mua cả sữa chua, dưa lê.", imagePrompt: "Mẹ dắt tay Hà bước vào lớp học múa" },
  { id: 26, title: "Bài 26: ph qu", letters: ["ph", "qu"], recognitionSentence: "Hà vẽ phố xá, quê nhà.", vocabulary: ["phố cổ", "quà quê", "phở bò"], readingText: "Quê Hà có phố cổ. Nhà Hà có phở bò.", imagePrompt: "Cảnh phố cổ Hội An rực rỡ lồng đèn" },
  { id: 27, title: "Bài 27: v x", letters: ["v", "x"], recognitionSentence: "Vẽ về xóm nhỏ vui vẻ.", vocabulary: ["vỏ đỗ", "xe chở đá", "xôi vò"], readingText: "Bé về quê ngoại chơi. Quê ngoại có xe chở đá.", imagePrompt: "Xóm làng thanh bình với những khóm tre" },
  { id: 28, title: "Bài 28: y p", letters: ["y", "p"], recognitionSentence: "Y tá chăm sóc bệnh nhân.", vocabulary: ["y tế", "đèn tuýp", "xe píp"], readingText: "Chị Hà là y tá. Chị rất chăm chỉ.", imagePrompt: "Cô y tá đang mỉm cười dịu dàng" },
  { id: 31, title: "Bài 31: an ăn ân", letters: ["an", "ăn", "ân"], recognitionSentence: "Ngựa vằn và hươu cao cổ là đôi bạn thân.", vocabulary: ["bản", "nhãn", "gần", "bạn thân"], readingText: "Đàn gà cứ tha thẩn gần chân mẹ. Đã có mẹ che chắn.", imagePrompt: "Ngựa vằn và hươu cao cổ đứng cạnh nhau trong rừng" },
  { id: 32, title: "Bài 32: on ôn ơn", letters: ["on", "ôn", "ơn"], recognitionSentence: "Sơn ca véo von: Mẹ ơi, con đã lớn khôn.", vocabulary: ["giòn", "ngon", "bốn", "sơn ca"], readingText: "Bốn chú lợn con / Ve vẻ vè ve / Về bốn chú lợn / Nhởn nhơ nô giỡn.", imagePrompt: "Chim sơn ca đậu trên cành cây, phía dưới là mẹ sơn ca" },
  { id: 33, title: "Bài 33: en ên in un", letters: ["en", "ên", "in", "un"], recognitionSentence: "Cún con nhìn thấy dế mèn trên tàu lá.", vocabulary: ["khen", "sen", "nến", "đèn pin"], readingText: "Con gì tên rõ là 'cha' / Có chứa chữ số nhìn qua ngỡ rùa?", imagePrompt: "Chú cún con đang tò mò nhìn một chú dế mèn" },
  { id: 34, title: "Bài 34: am âm am", letters: ["am", "âm"], recognitionSentence: "Sáng sớm, Nam đi cắm trại.", vocabulary: ["cam", "nấm", "mâm"], readingText: "Cả lớp đi cắm trại ở núi Lam. Trời rất xanh.", imagePrompt: "Các bạn nhỏ đang dựng lều cắm trại" },
  { id: 36, title: "Bài 36: om ôm ơm", letters: ["om", "ôm", "ơm"], recognitionSentence: "Hương cốm thơm thôn xóm.", vocabulary: ["khóm", "vòm", "tôm", "đom đóm"], readingText: "Hôm qua, cô Mơ ở xóm Hạ đến thăm nhà Hà. Cô cho Hà giỏ cam.", imagePrompt: "Cảnh làng quê yên bình với những bó rơm vàng rực" },
  { id: 37, title: "Bài 37: em êm im um", letters: ["em", "êm", "im", "un"], recognitionSentence: "Bé xem phim hoạt hình.", vocabulary: ["tem", "đệm", "chim", "chùm"], readingText: "Bố xem phim. Bé tìm chim.", imagePrompt: "Bé ngồi xem tivi cùng bố" },
  { id: 38, title: "Bài 38: ai ay ây", letters: ["ai", "ay", "ây"], recognitionSentence: "Hai bạn thi nhảy dây.", vocabulary: ["bài", "lái", "tay", "đám mây"], readingText: "Nai con nhìn thấy con gì bé nhỏ, thân đầy gai nhọn trên bãi cỏ.", imagePrompt: "Hai bé gái đang tươi cười nhảy dây trong sân trường" },
  { id: 39, title: "Bài 39: oi ôi ơi", letters: ["oi", "ôi", "ơi"], recognitionSentence: "Đồ chơi mới cho bé.", vocabulary: ["tỏi", "thổi", "bơi"], readingText: "Bé có đồ chơi mới. Bé bơi ở hồ.", imagePrompt: "Bé đang chơi với mô hình tàu thủy" },
  { id: 41, title: "Bài 41: ui ưi", letters: ["ui", "ưi"], recognitionSentence: "Bà gửi cho Hà túi kẹo.", vocabulary: ["bùi", "mũi", "gửi", "gửi thư"], readingText: "Lan gửi thư cho Hà kể về quê Lan. Ở đó, có nhà sàn ven đồi.", imagePrompt: "Hà đang háo hức mở túi kẹo đầy màu sắc mà bà gửi tặng" },
  { id: 42, title: "Bài 42: ao eo", letters: ["ao", "eo"], recognitionSentence: "Ngôi sao cao vút.", vocabulary: ["chào", "kẹo", "mèo"], readingText: "Mèo con trèo cao. Bé chào mẹ.", imagePrompt: "Chú mèo đang trèo lên cây cau" },
  { id: 43, title: "Bài 43: au âu iu", letters: ["au", "âu", "iu"], recognitionSentence: "Cầu vồng sau cơn mưa.", vocabulary: ["rau", "cầu", "rìu"], readingText: "Sau mưa có cầu vồng. Bé yêu bà.", imagePrompt: "Cầu vồng rực rỡ hiện ra sau rặng tre" },
  { id: 44, title: "Bài 44: ưu hươu", letters: ["ưu", "ươu"], recognitionSentence: "Chú hươu sao hiền lành.", vocabulary: ["cừu", "hươu", "rượu"], readingText: "Đàn cừu gặm cỏ. Hươu chạy nhanh.", imagePrompt: "Đàn cừu trắng đang nhẩn nha ăn cỏ" },
  { id: 46, title: "Bài 46: ac ăc âc", letters: ["ac", "ăc", "âc"], recognitionSentence: "Tây Bắc có ruộng bậc thang, có thác nước.", vocabulary: ["lạc", "mặc", "gấc", "bác sĩ"], readingText: "Nếu lên Tây Bắc, bạn hãy đến Sa Pa. Sa Pa có Thác Bạc, có Cầu Mây.", imagePrompt: "Những dải ruộng bậc thang xanh mướt uốn lượn trên đồi núi" },
  { id: 47, title: "Bài 47: oc ôc uc ưc", letters: ["oc", "ôc", "uc", "ưc"], recognitionSentence: "Học bài dưới gốc cây.", vocabulary: ["đọc", "gốc", "cúc", "mực"], readingText: "Bé học bài. Gốc cây có hoa cúc.", imagePrompt: "Bé ngồi học bài dưới bóng cây mát rượi" },
  { id: 48, title: "Bài 48: at ăt ât", letters: ["at", "ăt", "ât"], recognitionSentence: "Bé hát bài hát mới.", vocabulary: ["hát", "mắt", "tất"], readingText: "Bé hát bài 'Mẹ yêu'. Mắt bé sáng ngời.", imagePrompt: "Bé đang biểu diễn hát trên bục giảng" },
  { id: 49, title: "Bài 49: ot ôt ơt", letters: ["ot", "ôt", "ơt"], recognitionSentence: "Quả ớt cay xè.", vocabulary: ["hót", "thốt", "ớt"], readingText: "Chim hót líu lo. Quả ớt đỏ thắm.", imagePrompt: "Chim họa mi đang hót trên cành ớt" },
  { id: 51, title: "Bài 51: et êt it", letters: ["et", "êt", "it"], recognitionSentence: "Đôi vẹt ríu rít mãi không hết chuyện.", vocabulary: ["két", "sét", "tết", "quả mít"], readingText: "Tết đến thật gần. Cái rét vẫn đậm. Mấy cây đào đã chi chít lộc non.", imagePrompt: "Hai chú vẹt sặc sỡ đang đậu trên cành cây" },
  { id: 52, title: "Bài 52: ut ưt", letters: ["ut", "ưt"], recognitionSentence: "Bé bút mực mới.", vocabulary: ["bút", "mứt", "rút"], readingText: "Bé có bút mực. Tết có mứt dừa.", imagePrompt: "Bé đang khoe chiếc bút mực đẹp" },
  { id: 53, title: "Bài 53: ap ăp âp", letters: ["ap", "ăp", "âp"], recognitionSentence: "Bé tập múa hát.", vocabulary: ["tháp", "cặp", "tập"], readingText: "Bé tập múa. Bé có cặp mới.", imagePrompt: "Bé đang múa điệu múa xòe hoa" },
  { id: 54, title: "Bài 54: op ôp ơp", letters: ["op", "ôp", "ơp"], recognitionSentence: "Bé họp nhóm học tập.", vocabulary: ["họp", "hộp", "lớp"], readingText: "Lớp bé họp nhóm. Bé có hộp quà.", imagePrompt: "Các bé đang ngồi thảo luận nhóm" },
  { id: 56, title: "Bài 56: ep êp ip up", letters: ["ep", "êp", "ip", "up"], recognitionSentence: "Bé xép hình ngôi nhà.", vocabulary: ["dép", "bếp", "nhịp", "búp"], readingText: "Mẹ ở bếp. Bé có dép mới.", imagePrompt: "Bé đang xếp những khối gỗ màu sắc" },
  { id: 57, title: "Bài 57: anh ênh inh", letters: ["anh", "ênh", "inh"], recognitionSentence: "Con kênh xinh xinh chảy qua cánh đồng.", vocabulary: ["chanh", "kênh", "kính", "quả chanh"], readingText: "Nhà vịt ở gần một con kênh xinh xinh. Bố mẹ cho vịt con ra tập bơi.", imagePrompt: "Dòng kênh nhỏ uốn lượn giữa cánh đồng lúa chín vàng" },
  { id: 58, title: "Bài 58: ach êch ich", letters: ["ach", "êch", "ich"], recognitionSentence: "Bé đọc sách thư viện.", vocabulary: ["sách", "ếch", "đích"], readingText: "Bé đọc sách. Ếch kêu ộp ộp.", imagePrompt: "Bé đang ngồi trong thư viện đầy sách" },
  { id: 59, title: "Bài 59: ang ăng âng", letters: ["ang", "ăng", "âng"], recognitionSentence: "Sáng sớm, nắng lên cao.", vocabulary: ["bảng", "trăng", "vâng"], readingText: "Nắng lên sáng rực. Bé vâng lời mẹ.", imagePrompt: "Ánh nắng ban mai xuyên qua tán lá" },
  { id: 61, title: "Bài 61: ong ông ung ưng", letters: ["ong", "ông", "ung", "ưng"], recognitionSentence: "Những bông hồng rung rinh trong gió.", vocabulary: ["dòng", "thúng", "đựng", "bánh chưng"], readingText: "Nam theo mẹ đi chợ. Chợ đông vui và bán đủ thứ. Nam thích lắm.", imagePrompt: "Vườn hoa hồng đỏ rực rỡ đang đung đưa trước gió" },
  { id: 62, title: "Bài 62: iêc iên iêt", letters: ["iêc", "iên", "iêt"], recognitionSentence: "Bé viết bài tiếng Việt.", vocabulary: ["tiệc", "tiên", "viết"], readingText: "Bé viết bài. Cô tiên dịu dàng.", imagePrompt: "Bé đang nắn nót viết chữ đẹp" },
  { id: 63, title: "Bài 63: iêng iêm iên", letters: ["iêng", "iêm", "iên"], recognitionSentence: "Tiếng chim hót líu lo.", vocabulary: ["chiêng", "tiệm", "biển"], readingText: "Tiếng chim hót. Biển xanh mênh mông.", imagePrompt: "Bé đang đứng trước bãi biển xanh" },
  { id: 64, title: "Bài 64: iêp iêu", letters: ["iêp", "iêu"], recognitionSentence: "Bé yêu mẹ nhất.", vocabulary: ["tiếp", "diều", "yêu"], readingText: "Bé thả diều. Bé yêu gia đình.", imagePrompt: "Bé đang thả diều trên cánh đồng" },
  { id: 66, title: "Bài 66: uôi uôm", letters: ["uôi", "uôm"], recognitionSentence: "Thuyền buồm xuôi theo chiều gió.", vocabulary: ["muối", "buồm", "tuổi", "con suối"], readingText: "Buổi sớm mai, ông mặt trời nhô lên từ biển. Mặt biển nhuộm xanh biếc.", imagePrompt: "Những chiếc thuyền buồm rực rỡ đang căng gió trôi trên biển" },
  { id: 67, title: "Bài 67: uôn uôt", letters: ["uôn", "uôt"], recognitionSentence: "Dòng suối cuồn cuộn.", vocabulary: ["muộn", "chuột", "tuốt"], readingText: "Suối chảy cuồn cuộn. Chuột túi chạy nhanh.", imagePrompt: "Dòng suối chảy xiết giữa rừng" },
  { id: 68, title: "Bài 68: uông uôc", letters: ["uông", "uôc"], recognitionSentence: "Bé uống sữa mỗi ngày.", vocabulary: ["chuông", "đuốc", "uống"], readingText: "Tiếng chuông vang. Bé uống sữa.", imagePrompt: "Bé đang cầm ly sữa uống ngon lành" },
  { id: 69, title: "Bài 69: ươn ươt", letters: ["ươn", "ươt"], recognitionSentence: "Khu vườn có nhiều hoa.", vocabulary: ["vườn", "lướt", "mượn"], readingText: "Vườn có hoa hồng. Bé lướt ván.", imagePrompt: "Khu vườn đầy hoa và bướm bay" },
  { id: 71, title: "Bài 71: ươc ươt", letters: ["ươc", "ươt"], recognitionSentence: "Hà ước được lướt sóng biển.", vocabulary: ["bước", "lướt", "nước", "thước kẻ"], readingText: "Lúc học hát, Nam ước làm ca sĩ. Lúc nghe mẹ đọc thơ, Nam ước là nhà thơ.", imagePrompt: "Bé Hà đang nhắm mắt mơ màng, hiện ra hình ảnh bé đang lướt sóng" },
  { id: 72, title: "Bài 72: ươm ươp", letters: ["ươm", "ươp"], recognitionSentence: "Bướm bay lượn trong vườn.", vocabulary: ["bướm", "mướp", "lượm"], readingText: "Bướm bay trong vườn mướp. Bé lượm hoa.", imagePrompt: "Những chú bướm đầy màu sắc bay quanh giàn mướp" },
  { id: 73, title: "Bài 73: ương ươc", letters: ["ương", "ươc"], recognitionSentence: "Con đường làng uốn lượn.", vocabulary: ["đường", "thước", "lượng"], readingText: "Đường làng sạch đẹp. Bé có thước kẻ.", imagePrompt: "Con đường làng trải bê tông sạch sẽ" },
  { id: 74, title: "Bài 74: oa oe", letters: ["oa", "oe"], recognitionSentence: "Các loài hoa đua nhau khoe sắc.", vocabulary: ["hoà", "khoẻ", "xoá", "đoá hoa"], readingText: "Tết đến, hoa đào khoe sắc hồng tươi. Hè sang, hoa phượng bừng lửa đỏ.", imagePrompt: "Vườn hoa đầy đủ các loại hoa đang nở rực rỡ dưới ánh nắng" },
  { id: 76, title: "Bài 76: oai oay", letters: ["oai", "oay"], recognitionSentence: "Quả xoài chín vàng.", vocabulary: ["xoài", "loay hoay", "khoai"], readingText: "Bé ăn xoài. Bố loay hoay sửa xe.", imagePrompt: "Bé đang cầm quả xoài chín mọng" },
  { id: 77, title: "Bài 77: oăn oăt", letters: ["oăn", "oăt"], recognitionSentence: "Tóc bé xoăn tự nhiên.", vocabulary: ["xoăn", "thoắt", "ngoắt"], readingText: "Tóc bé xoăn. Sóc nhảy thoắt cái.", imagePrompt: "Bé gái có mái tóc xoăn đáng yêu" },
  { id: 78, title: "Bài 78: uân uât", letters: ["uân", "uât"], recognitionSentence: "Mùa xuân về ấm áp.", vocabulary: ["xuân", "luật", "thuật"], readingText: "Xuân về hoa nở. Bé học luật giao thông.", imagePrompt: "Cảnh mùa xuân với hoa đào hoa mai" },
  { id: 79, title: "Bài 79: uyên uyêt", letters: ["uyên", "uyêt"], recognitionSentence: "Bà kể chuyện hay tuyệt.", vocabulary: ["chuyền", "duyệt", "truyện", "con thuyền"], readingText: "Trăng sáng / Sân nhà em sáng quá / Nhờ ánh trăng sáng ngời. / Trăng tròn như cái đĩa.", imagePrompt: "Bà và cháu đang ngồi trên chõng tre ngoài sân, bà kể chuyện cổ tích" },
  { id: 81, title: "Bài 81: uynh uych", letters: ["uynh", "uych"], recognitionSentence: "Tiếng chạy huỳnh huỵch.", vocabulary: ["phụ huynh", "huỵch", "quỳnh"], readingText: "Họp phụ huynh. Bé chạy huỳnh huỵch.", imagePrompt: "Các bé đang chạy nhảy vui đùa" },
  { id: 82, title: "Bài 82: uơ uya", letters: ["uơ", "uya"], recognitionSentence: "Đêm khuya trăng sáng.", vocabulary: ["khuya", "huơ", "thuở"], readingText: "Đêm đã khuya. Bé huơ tay chào.", imagePrompt: "Cảnh bầu trời đêm với ánh trăng khuyết" },
  { id: 83, title: "Bài 83: Ôn tập cuối học kỳ 1", letters: ["tổng hợp"], recognitionSentence: "Chào tạm biệt học kỳ 1.", vocabulary: ["kết quả", "niềm vui", "nghỉ tết"], readingText: "Học kỳ 1 đã qua. Em rất vui vì đã học được nhiều điều hay.", imagePrompt: "Bé nhận được phiếu khen và nụ cười rạng rỡ của bố mẹ" },

  // ================= TẬP 2: BÀI ĐỌC THEO CHỦ ĐỀ (10 CHỦ ĐỀ) =================
  {
    id: 101,
    title: "Chủ đề 1: Tôi và các bạn - Tôi là học sinh lớp 1",
    letters: ["đọc"],
    recognitionSentence: "Ngày đầu đi học bé cảm thấy thế nào?",
    vocabulary: ["đồng phục", "hãnh diện", "chững chạc"],
    readingText: "Tôi tên là Nam, học sinh lớp 1A. Ngày đầu đi học, mặc bộ đồng phục mới, tôi thấy mình thật hãnh diện. Bây giờ tôi đã biết đọc, biết viết và có rất nhiều bạn mới.",
    speakingTopic: "Giới thiệu về bản thân bé",
    imagePrompt: "Bé trai mặc đồng phục học sinh lớp 1, tay cầm sách, vẻ mặt tự tin hãnh diện"
  },
  {
    id: 102,
    title: "Chủ đề 2: Mái ấm gia đình - Nụ hôn trên bàn tay",
    letters: ["đọc"],
    recognitionSentence: "Mẹ đã làm gì để Nam bớt lo lắng?",
    vocabulary: ["hồi hộp", "thủ thỉ", "ấm áp"],
    readingText: "Mẹ nhẹ nhàng đặt một nụ hôn vào lòng bàn tay Nam. Mỗi khi lo lắng, Nam áp bàn tay lên má. Nam thấy mẹ như luôn ở bên cạnh mình.",
    speakingTopic: "Kể về tình yêu của mẹ dành cho bé",
    imagePrompt: "Người mẹ đang dịu dàng hôn vào bàn tay nhỏ bé của con trai"
  },
  {
    id: 103,
    title: "Chủ đề 3: Mái trường thân yêu - Đi học",
    letters: ["thơ"],
    recognitionSentence: "Bạn nhỏ đi học qua những cảnh đẹp nào?",
    vocabulary: ["hương rừng", "dòng suối", "cọ xòe"],
    readingText: "Hương rừng thơm đồi vắng / Nước suối trong thầm thì / Cọ xòe ô che nắng / Râm mát đường em đi.",
    speakingTopic: "Mô tả con đường đi học hàng ngày của bé",
    imagePrompt: "Bạn nhỏ đội mũ đi học trên con đường ven suối có cây cọ xòe lá"
  },
  {
    id: 104,
    title: "Chủ đề 4: Điều em học được - Mỗi người một việc",
    letters: ["đọc"],
    recognitionSentence: "Trong lớp học, các đồ vật làm việc gì?",
    vocabulary: ["nhộn nhịp", "chăm chỉ", "vui vẻ"],
    readingText: "Cây bút vẽ hoa. Quyển vở ghi bài. Thước kẻ kẻ đường thẳng. Ai cũng làm việc chăm chỉ để giúp bé học tốt.",
    speakingTopic: "Đồ dùng học tập yêu thích của bé",
    imagePrompt: "Các đồ dùng học tập: bút, thước, vở có gương mặt hoạt hình đang vui vẻ làm việc"
  },
  {
    id: 105,
    title: "Chủ đề 5: Thiên nhiên tươi đẹp - Bảy sắc cầu vồng",
    letters: ["thơ"],
    recognitionSentence: "Cầu vồng xuất hiện khi nào?",
    vocabulary: ["rực rỡ", "vừa mưa lại nắng", "lung linh"],
    readingText: "Vừa mưa lại nắng / Hay có cầu vồng / Bảy màu tươi thắm / Bé mừng vui trông. / Đỏ, cam, vàng, lục / Lam, chàm, tím xinh.",
    speakingTopic: "Bé hãy kể tên 7 màu của cầu vồng",
    imagePrompt: "Cầu vồng bảy màu rực rỡ hiện lên trên cánh đồng sau cơn mưa"
  },
  {
    id: 106,
    title: "Chủ đề 6: Thiên nhiên kì thú - Loài chim của biển cả",
    letters: ["iên", "yêt"],
    recognitionSentence: "Chim hải âu thường sống ở đâu?",
    vocabulary: ["sải cánh", "đại dương", "báo bão"],
    readingText: "Hải âu là loài chim của biển cả. Chúng có sải cánh lớn, bay rất xa. Hải âu còn được gọi là bạn của những người đi biển vì chúng báo hiệu khi bão sắp đến.",
    speakingTopic: "Kể tên các loài chim mà bé biết",
    imagePrompt: "Chim hải âu trắng sải cánh bay trên mặt biển đại dương xanh biếc"
  },
  {
    id: 107,
    title: "Chủ đề 7: Thế giới trong mắt em - Ong xây tổ",
    letters: ["ong", "ông"],
    recognitionSentence: "Bầy ong làm việc như thế nào?",
    vocabulary: ["đoàn kết", "kiên trì", "ngọt ngào"],
    readingText: "Bầy ong chăm chỉ hút mật hoa mang về xây tổ. Nhờ sự đoàn kết, tổ ong ngày càng to và chứa đầy mật ngọt.",
    speakingTopic: "Bé học được điều gì từ bầy ong?",
    imagePrompt: "Đàn ong đang bay quanh tổ ong vàng óng trên cành cây"
  },
  {
    id: 108,
    title: "Chủ đề 8: Đất nước và con người - Hà Nội",
    letters: ["đọc"],
    recognitionSentence: "Hà Nội có những cảnh đẹp nào?",
    vocabulary: ["Thủ đô", "Hồ Gươm", "Tháp Rùa"],
    readingText: "Hà Nội là Thủ đô của nước ta. Nơi đây có Hồ Gươm xanh ngắt, có Tháp Rùa cổ kính và những con phố cổ nhộn nhịp người qua lại.",
    speakingTopic: "Bé biết gì về Thủ đô Hà Nội?",
    imagePrompt: "Cảnh Hồ Gươm với Tháp Rùa và cầu Thê Húc màu đỏ rực rỡ"
  },
  {
    id: 109,
    title: "Chủ đề 9: Những trải nghiệm thú vị - Buổi học thể dục",
    letters: ["đọc"],
    recognitionSentence: "Buổi học thể dục diễn ra như thế nào?",
    vocabulary: ["vận động", "khỏe mạnh", "nhanh nhẹn"],
    readingText: "Hôm nay chúng em có buổi học thể dục. Các bạn cùng nhau chạy bộ, nhảy dây và chơi bóng chuyền. Ai cũng thấy khỏe khoắn và vui vẻ.",
    speakingTopic: "Môn thể thao bé yêu thích",
    imagePrompt: "Các bé đang chơi đùa trên sân vận động trường học"
  },
  {
    id: 110,
    title: "Chủ đề 10: Ước mơ của em - Ước mơ của bé",
    letters: ["đọc"],
    recognitionSentence: "Bé ước mơ lớn lên sẽ làm gì?",
    vocabulary: ["bác sĩ", "phi công", "giáo viên"],
    readingText: "Bé ước mơ lớn lên sẽ trở thành một phi công để bay lượn trên bầu trời cao rộng, khám phá những vùng đất mới lạ.",
    speakingTopic: "Ước mơ của bé khi lớn lên",
    imagePrompt: "Bé trai đang mặc bộ đồ phi công đứng cạnh mô hình máy bay"
  }
];
